#!/usr/local/bin/python
import smtplib
smtp = {}
smtp['hostname'] = 'smtp.u.inova.com.br'
smtp['port'] = 587
smtp['username'] = 'fernando.cainelli@velop.net'
smtp['password'] = '123Sta+His123'
smtp['from'] = 'fernando.cainelli@velop.net'
smtp['to'] = 'fernando@cainelli.me'

if __name__ == '__main__':

  server = smtplib.SMTP(host=smtp['hostname'], port=smtp['port'])
  server.login(smtp['username'], smtp['password'])

  with open ('msg.eml', 'r') as f:
    msg = f.read()

  server.sendmail(smtp['from'], smtp['to'], msg)

